### ISSUE TITLE
Exception in System -> Cache management with v2.0.6 on Magento 2.2.0

### ISSUE THREAD

**Issue by sindrepm** [litespeedtech/magento2-LiteSpeed_LiteMage#14]
Just installed Litemage v2.0.6 on a relatively fresh Magento 2.2.0 install. Installation went fine and seems caching is working, but when I go to System -> Cache Management in admin panel I get this stack trace:

```
1 exception(s):
Exception #0 (Zend_Http_Client_Exception): Unable to read response, or response is empty

Exception #0 (Zend_Http_Client_Exception): Unable to read response, or response is empty
#0 /home/anonuser/public_html/vendor/magento/framework/HTTP/ZendClient.php(52): Zend_Http_Client->request(NULL)
#1 /home/anonuser/public_html/app/code/Litespeed/Litemage/Block/Backend/Cache/Management.php(105): Magento\Framework\HTTP\ZendClient->request()
#2 /home/anonuser/public_html/app/code/Litespeed/Litemage/view/adminhtml/templates/system/cache/litemage.phtml(38): Litespeed\Litemage\Block\Backend\Cache\Management->getCacheStatistics()
#3 /home/anonuser/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/anonuser...')
#4 /home/anonuser/public_html/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Litespeed\Litemage\Block\Backend\Cache\Management), '/home/anonuser...', Array)
#5 /home/anonuser/public_html/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/home/anonuser...')
#6 /home/anonuser/public_html/vendor/magento/module-backend/Block/Template.php(124): Magento\Framework\View\Element\Template->_toHtml()
#7 /home/anonuser/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Backend\Block\Template->_toHtml()
#8 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#9 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('cache.litemage')
#10 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('cache.litemage')
#11 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('cache.litemage')
#12 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('content')
#13 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('content')
#14 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('content')
#15 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main.col')
#16 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#17 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('main.col')
#18 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...')
#19 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#20 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('admin.scope.col...')
#21 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#22 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#23 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('page.main.conta...')
#24 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.content')
#25 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#26 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('page.content')
#27 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#28 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#29 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('page.wrapper')
#30 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('backend.page')
#31 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#32 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('backend.page')
#33 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('root')
#34 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('root')
#35 /home/anonuser/public_html/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout->renderElement('root')
#36 /home/anonuser/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(37): Magento\Framework\View\Layout->getOutput()
#37 /home/anonuser/public_html/vendor/magento/framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#38 /home/anonuser/public_html/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#39 /home/anonuser/public_html/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(37): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#40 /home/anonuser/public_html/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#41 /home/anonuser/public_html/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#42 /home/anonuser/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#43 {main}
```
Any idea?

**Comment by litespeedtech** [comment]
Can you do a quick test, modify this file Litespeed/Litemage/Block/Backend/Cache/Management.php
replace url with _urlBuilder on line 84  
change from 
`$base = $this->url->getBaseUrl();`
to
`$base = $this->_urlBuilder->getBaseUrl();`
Let me know if it works

**Comment by litespeedtech** [comment]
Thanks for reporting. I've identified the issue. It was caused by Magento library change.
I'll make a new release soon.
