### ISSUE TITLE
"Area code not set" on page load.

### ISSUE THREAD

**Issue by lingwooc** [litespeedtech/magento2-LiteSpeed_LiteMage#9]
I'm getting the following message in my exception log on every page load. Other than this the site works as expected. I'm using your plugin v2.0.3 and magento 2.1.3. I've done a clean install on a different server. Same issue. If I disable the litemage module the error goes away and the site slows down (so it is working to some extent).

The command line cache flush command works fine with this version.

The truncated args are not helpful but I can't work out how to untruncate them.

```
Next Magento\Framework\Exception\SessionException: Area code not set: Area code must be set before starting a session. in /home/dtecgtk/public_html/vendor/magento/framework/Session/SessionManager.php:175
Stack trace:
#0 /home/dtecgtk/public_html/var/generation/Magento/Framework/Session/Generic/Interceptor.php(50): Magento\Framework\Session\SessionManager->start()
#1 /home/dtecgtk/public_html/vendor/magento/framework/Session/SessionManager.php(130): Magento\Framework\Session\Generic\Interceptor->start()
#2 /home/dtecgtk/public_html/var/generation/Magento/Framework/Session/Generic/Interceptor.php(14): Magento\Framework\Session\SessionManager->__construct(Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\Session\SidResolver\Proxy), Object(Magento\Framework\Session\Config), Object(Magento\Framework\Session\SaveHandler), Object(Magento\Framework\Session\Validator), Object(Magento\Framework\Session\Storage), Object(Magento\Framework\Stdlib\Cookie\PhpCookieManager), Object(Magento\Framework\Stdlib\Cookie\CookieMetadataFactory), Object(Magento\Framework\App\State))
#3 /home/dtecgtk/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Magento\Framework\Session\Generic\Interceptor->__construct(Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\Session\SidResolver\Proxy), Object(Magento\Framework\Session\Config), Object(Magento\Framework\Session\SaveHandler), Object(Magento\Framework\Session\Validator), Object(Magento\Framework\Session\Storage), Object(Magento\Framework\Stdlib\Cookie\PhpCookieManager), Object(Magento\Framework\Stdlib\Cookie\CookieMetadataFactory), Object(Magento\Framework\App\State))
#4 /home/dtecgtk/public_html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#5 /home/dtecgtk/public_html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(130): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...')
#6 /home/dtecgtk/public_html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(67): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Framewo...')
#7 /home/dtecgtk/public_html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(130): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Store\\A...')
#8 /home/dtecgtk/public_html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(67): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Store\\A...')
#9 /home/dtecgtk/public_html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(130): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...')
#10 /home/dtecgtk/public_html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(67): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Framewo...')
#11 /home/dtecgtk/public_html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(130): Magento\Framework\ObjectManager\Factory\Compiled->create('Litespeed\\Litem...')
#12 /home/dtecgtk/public_html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(67): Magento\Framework\ObjectManager\Factory\Compiled->get('Litespeed\\Litem...')
#13 /home/dtecgtk/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Compiled->create('Litespeed\\Litem...')
#14 /home/dtecgtk/public_html/vendor/magento/framework/Interception/PluginList/PluginList.php(232): Magento\Framework\ObjectManager\ObjectManager->get('Litespeed\\Litem...')
#15 /home/dtecgtk/public_html/vendor/magento/framework/Interception/Interceptor.php(121): Magento\Framework\Interception\PluginList\PluginList->getPlugin('Magento\\Framewo...', 'response-http-l...')
#16 /home/dtecgtk/public_html/var/generation/Magento/Framework/App/Response/Http/Interceptor.php(117): Magento\Framework\App\Response\Http\Interceptor->___callPlugins('sendResponse', Array, Array)
#17 /home/dtecgtk/public_html/pub/errors/404.php(12): Magento\Framework\App\Response\Http\Interceptor->sendResponse()
#18 /home/dtecgtk/public_html/vendor/magento/framework/App/StaticResource.php(114): require('/home/dtecgtk/p...')
#19 /home/dtecgtk/public_html/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\StaticResource->catchException(Object(Magento\Framework\App\Bootstrap), Object(Magento\Framework\Exception\SessionException))
#20 /home/dtecgtk/public_html/pub/static.php(13): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\StaticResource))
#21 {main} [] []
```

**Comment by litespeedtech** [comment]
I can reproduce this and will work on a fix.
Thanks for your report.
Lauren

**Comment by litespeedtech** [comment]
please email to info@litespeedtech.com to request adding to slack group.

For this issue, please remove di.xml from etc/, and put the same content under frontend/di.xml and adminhtml/di.xml. 
I'll include this in next push. Let me know if this works for you.

**Comment by litespeedtech** [comment]
updated with release 2.0.4, let me know if your issue got resolved.

**Comment by lingwooc** [comment]
Looks good! Just installed any my exception log is clear.
